version: 2.1
orbs:
  node: circleci/node@5.0.2
workflows:
  test:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "yarn.lock"}}
      - run:
          name: install packages
          command: yarn
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "yarn.lock"}}
          paths:
            - ~/.yarn
      - run:
          name: Run Lint
          command: yarn lint
      - run:
        name: Run Test
        command: yarn test
workflows:
  orb-free-workflow:
    jobs:
      - test